import type { TranscriptItem } from '../../../daemon/src/protocol';
import { buildGenericToolModel } from '../tool-render/generic-model';
import type { AppState, PendingInteraction, ServerEnvelope, ToolCard } from './types';

export const initialAppState: AppState = { connection:'connecting', workspaces:[], sessions:[], transcript:[], toolCards:{}, pendingInteractions:[], sessionState:{isStreaming:false}, queuedPrompts:[], drafts:{}, seenEvents:{}, lastSequences:{}, replayDone:{} };
const record = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const textOf = (content: unknown): string => typeof content === 'string' ? content : Array.isArray(content) ? content.filter((b) => record(b).type === 'text').map((b) => String(record(b).text ?? '')).join('\n') : '';
function messageItem(payload: Record<string, unknown>, fallback: string): TranscriptItem | null { const msg=record(payload.message); if (!Object.keys(msg).length) return null; const role=String(msg.role ?? 'assistant'); const timestamp=typeof msg.timestamp === 'number' ? msg.timestamp : undefined; const id=String(msg.id ?? msg.responseId ?? `${role}_${timestamp ?? fallback}`); return { id, kind: typeof msg.kind === 'string' ? msg.kind as TranscriptItem['kind'] : role === 'user' ? 'user' : role === 'toolResult' ? 'tool' : 'assistant', role, text:typeof msg.text === 'string' ? msg.text : textOf(msg.content), timestamp, toolName:typeof msg.toolName === 'string'?msg.toolName:undefined, toolCallId:typeof msg.toolCallId === 'string'?msg.toolCallId:undefined, toolResult: role === 'toolResult' ? {content: msg.content,details:msg.details}:undefined, isError:msg.isError === true }; }
function upsert(items: TranscriptItem[], item: TranscriptItem): TranscriptItem[] { const at=items.findIndex((x)=>x.id===item.id); return at < 0 ? [...items,item] : items.map((x,i)=>i===at?{...x,...item}:x); }
function card(payload: Record<string, unknown>, old?: ToolCard, state?: ToolCard['state']): ToolCard { const toolCallId=String(payload.toolCallId ?? old?.toolCallId ?? 'unknown'); const next: ToolCard={ toolCallId, toolName:String(payload.toolName ?? old?.toolName ?? 'Unknown tool'), args:payload.args ?? old?.args, partialResult:payload.partialResult ?? old?.partialResult, result:payload.result ?? old?.result, state: state ?? old?.state ?? 'running', isError:payload.isError === true || old?.isError, startedAt:old?.startedAt ?? Date.now(), endedAt:state && state !== 'running' ? Date.now() : old?.endedAt, collapsed:old?.collapsed}; const generic=buildGenericToolModel({toolCallId:next.toolCallId,toolName:next.toolName,args:next.args,state:next.state,partialResult:next.partialResult,result:next.result,isError:next.isError,startedAt:next.startedAt,endedAt:next.endedAt}); return {...next, collapsed: generic.displayText.length > 4096}; }
export function applyServerEvent(state: AppState, event: ServerEnvelope): AppState { const key=event.eventId ?? (event.sequence !== undefined && event.sessionId ? `${event.sessionId}:${event.sequence}` : undefined); if(key && state.seenEvents[key]) return state; const payload=record(event.payload); let next:AppState={...state, seenEvents:key?{...state.seenEvents,[key]:true}:state.seenEvents, lastSequences:event.sessionId && event.sequence !== undefined?{...state.lastSequences,[event.sessionId]:Math.max(state.lastSequences[event.sessionId]??0,event.sequence)}:state.lastSequences}; if(event.sessionId&&state.replayDone[event.sessionId]===false&&event.type!=='session.snapshot'&&event.type!=='replay.completed')return next;
 switch(event.type){
 case 'session.snapshot': { const items=Array.isArray(payload.items)?payload.items as TranscriptItem[]:[]; return {...next, transcript:items, toolCards:items.filter(x=>x.kind==='tool'&&x.toolCallId).reduce<Record<string,ToolCard>>((m,x)=>({...m,[x.toolCallId!]:{toolCallId:x.toolCallId!,toolName:x.toolName??'Unknown tool',args:x.toolArgs,result:x.toolResult,state:x.toolState??'success',isError:x.isError,collapsed:buildGenericToolModel({toolCallId:x.toolCallId,toolName:x.toolName,args:x.toolArgs,result:x.toolResult,state:x.toolState}).displayText.length>4096}}),{}), activeSession:payload.sessionId&&payload.sessionFile?{sessionId:String(payload.sessionId),sessionFile:String(payload.sessionFile)}:state.activeSession,replayDone:event.sessionId?{...state.replayDone,[event.sessionId]:false}:state.replayDone}; }
 case 'message.started': case 'message.delta': case 'message.completed': case 'message.failed': { const item=messageItem(payload,event.eventId??String(event.sequence??Date.now())); if(!item) return next; const failed=event.type==='message.failed'; return {...next, transcript:upsert(next.transcript,{...item,isError:failed||item.isError,kind:failed?'error':item.kind}), sessionState:{...next.sessionState,isStreaming:event.type==='message.completed'||failed?false:next.sessionState.isStreaming}}; }
 case 'tool.started': case 'tool.updated': case 'tool.completed': case 'tool.failed': { const id=String(payload.toolCallId??'unknown'); const stateValue=event.type==='tool.failed'?'failure':event.type==='tool.completed'?'success':'running'; const c=card(payload,next.toolCards[id],stateValue); const toolItem:TranscriptItem={id:`tool_${id}`,kind:'tool',text:'',toolCallId:id,toolName:c.toolName,toolState:c.state,toolArgs:c.args,toolResult:c.result??c.partialResult,isError:c.isError}; return {...next, toolCards:{...next.toolCards,[id]:c}, transcript:upsert(next.transcript,toolItem)}; }
 case 'approval.requested': case 'question.requested': { const id=String(payload.id ?? payload.interactionId ?? ''); if(!id) return next; if(payload.cancelled===true) return {...next,pendingInteractions:next.pendingInteractions.filter(x=>x.id!==id)}; const p:PendingInteraction={id,method:String(payload.method??''),kind:event.type.startsWith('approval')?'approval':'question',payload}; return {...next,pendingInteractions:next.pendingInteractions.some(x=>x.id===id)?next.pendingInteractions:[...next.pendingInteractions,p]}; }
 case 'status.updated': case 'context.updated': return {...next,sessionState:{...next.sessionState,...payload,isStreaming:typeof payload.isStreaming==='boolean'?payload.isStreaming:next.sessionState.isStreaming,statusMessage:typeof payload.message==='string'?payload.message:next.sessionState.statusMessage}};
 case 'todos.updated': case 'plan.updated': return {...next,sessionState:{...next.sessionState,todos:payload.todoPhases ?? payload.todos ?? payload}};
 case 'queue.updated': return {...next,queuedPrompts:Array.isArray(payload.messages)?payload.messages.map(String):next.queuedPrompts};
 case 'worker.starting': case 'worker.ready': case 'worker.stopped': case 'worker.crashed': return {...next,sessionState:{...next.sessionState,workerState:event.type.split('.')[1]}};
 case 'replay.completed': return {...next,replayDone:event.sessionId?{...next.replayDone,[event.sessionId]:true}:next.replayDone};
 default:return next; }
}
