import { describe, expect, it } from 'vitest';
import { applyServerEvent, initialAppState } from '../src/lib/reducer';
import { SEEN_EVENTS_LIMIT } from '../src/lib/reducer';
import { collapseTranscriptItems } from '../src/lib/transcript-collapse';
const event=(type:string,payload:unknown,extra:Record<string,unknown>={})=>({protocolVersion:1,type,payload,...extra}) as never;
describe('applyServerEvent',()=>{
 it('replaces transcript from snapshots',()=>{const s=applyServerEvent({...initialAppState,transcript:[{id:'old',kind:'user',text:'old'}]},event('session.snapshot',{sessionId:'s',sessionFile:'s.jsonl',items:[{id:'new',kind:'assistant',text:'new'}]}));expect(s.transcript).toEqual([{id:'new',kind:'assistant',text:'new'}]);expect(s.activeSession?.sessionId).toBe('s')});
 it('upserts message deltas idempotently',()=>{const e=event('message.delta',{message:{responseId:'r1',role:'assistant',content:[{type:'text',text:'complete'}]}},{eventId:'e1'});const one=applyServerEvent(initialAppState,e);const two=applyServerEvent(one,e);expect(two.transcript).toHaveLength(1);expect(two.transcript[0].text).toBe('complete')});
 it('tracks tool lifecycle and collapses large output',()=>{let s=applyServerEvent(initialAppState,event('tool.started',{toolCallId:'t',toolName:'unknown',args:{path:'src/a.ts'}}));s=applyServerEvent(s,event('tool.updated',{toolCallId:'t',partialResult:{content:[{type:'text',text:'x'.repeat(4097)}]}}));s=applyServerEvent(s,event('tool.completed',{toolCallId:'t',result:{content:[{type:'text',text:'done'}]}}));expect(s.toolCards.t.state).toBe('success');expect(s.transcript.filter(x=>x.toolCallId==='t')).toHaveLength(1);const big=applyServerEvent(initialAppState,event('tool.completed',{toolCallId:'big',toolName:'x',result:{content:[{type:'text',text:'x'.repeat(4097)}]}}));expect(big.toolCards.big.collapsed).toBe(true)});
 it('pushes and resolves pending interactions',()=>{let s=applyServerEvent(initialAppState,event('approval.requested',{id:'a1',method:'confirm',title:'Allow?'}));expect(s.pendingInteractions).toHaveLength(1);s=applyServerEvent(s,event('approval.requested',{id:'a1',cancelled:true}));expect(s.pendingInteractions).toHaveLength(0)});
 it('deduplicates replay events by sequence',()=>{const e=event('message.started',{message:{id:'m',role:'assistant',content:[{type:'text',text:'Hi'}]}},{sessionId:'s',sequence:2});const s=applyServerEvent(applyServerEvent(initialAppState,e),e);expect(s.transcript).toHaveLength(1);expect(s.lastSequences.s).toBe(2)});
 it('bounds seen events as an LRU and preserves sequence idempotency after eviction',()=>{let s=initialAppState;for(let i=0;i<SEEN_EVENTS_LIMIT+2;i++)s=applyServerEvent(s,event('status.updated',{message:String(i)},{eventId:`e${i}`,sessionId:'s',sequence:i+1}));expect(Object.keys(s.seenEvents)).toHaveLength(SEEN_EVENTS_LIMIT);expect(s.seenEvents.e0).toBeUndefined();const replay=applyServerEvent(s,event('status.updated',{message:'old'},{eventId:'e0',sessionId:'s',sequence:1}));expect(replay).toBe(s);});
 it('collapses only old render rows and keeps the latest 15 full',()=>{const items=Array.from({length:31},(_,i)=>({id:`m${i}`,kind:i%2?'assistant':'user',role:i%2?'assistant':'user',text:`message ${i}\\n\\nsecond block`})) as any;const rows=collapseTranscriptItems(items,new Set());expect(rows.filter(r=>r.type==='summary')).toHaveLength(16);expect(rows.slice(-15).every(r=>r.type==='full')).toBe(true);const expanded=collapseTranscriptItems(items,new Set(['m0']));expect(expanded[0].type).toBe('full');});
});
