import { describe, expect, it } from 'vitest';
import { applyServerEvent, initialAppState } from '../src/lib/reducer';
const event=(type:string,payload:unknown,extra:Record<string,unknown>={})=>({protocolVersion:1,type,payload,...extra}) as never;
describe('applyServerEvent',()=>{
 it('replaces transcript from snapshots',()=>{const s=applyServerEvent({...initialAppState,transcript:[{id:'old',kind:'user',text:'old'}]},event('session.snapshot',{sessionId:'s',sessionFile:'s.jsonl',items:[{id:'new',kind:'assistant',text:'new'}]}));expect(s.transcript).toEqual([{id:'new',kind:'assistant',text:'new'}]);expect(s.activeSession?.sessionId).toBe('s')});
 it('upserts message deltas idempotently',()=>{const e=event('message.delta',{message:{responseId:'r1',role:'assistant',content:[{type:'text',text:'complete'}]}},{eventId:'e1'});const one=applyServerEvent(initialAppState,e);const two=applyServerEvent(one,e);expect(two.transcript).toHaveLength(1);expect(two.transcript[0].text).toBe('complete')});
 it('tracks tool lifecycle and collapses large output',()=>{let s=applyServerEvent(initialAppState,event('tool.started',{toolCallId:'t',toolName:'unknown',args:{path:'src/a.ts'}}));s=applyServerEvent(s,event('tool.updated',{toolCallId:'t',partialResult:{content:[{type:'text',text:'x'.repeat(4097)}]}}));s=applyServerEvent(s,event('tool.completed',{toolCallId:'t',result:{content:[{type:'text',text:'done'}]}}));expect(s.toolCards.t.state).toBe('success');expect(s.transcript.filter(x=>x.toolCallId==='t')).toHaveLength(1);const big=applyServerEvent(initialAppState,event('tool.completed',{toolCallId:'big',toolName:'x',result:{content:[{type:'text',text:'x'.repeat(4097)}]}}));expect(big.toolCards.big.collapsed).toBe(true)});
 it('pushes and resolves pending interactions',()=>{let s=applyServerEvent(initialAppState,event('approval.requested',{id:'a1',method:'confirm',title:'Allow?'}));expect(s.pendingInteractions).toHaveLength(1);s=applyServerEvent(s,event('approval.requested',{id:'a1',cancelled:true}));expect(s.pendingInteractions).toHaveLength(0)});
 it('deduplicates replay events by sequence',()=>{const e=event('message.started',{message:{id:'m',role:'assistant',content:[{type:'text',text:'Hi'}]}},{sessionId:'s',sequence:2});const s=applyServerEvent(applyServerEvent(initialAppState,e),e);expect(s.transcript).toHaveLength(1);expect(s.lastSequences.s).toBe(2)});
});
